# Generated by Django 5.2 on 2025-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picutreUrl',
            field=models.URLField(default='https://img.freepik.com/freie-psd/restaurant-vintage-abzeichen-vorlagen-psd-set-remixed-aus-gemeinfreien-kunstwerken_53876-141767.jpg?t=st=1745589179~exp=1745592779~hmac=18565adbc457db41ae98630d4e960d602f2231fe3813bff947dd475a6f2ad99f&w=826'),
        ),
    ]
