# Generated by Django 5.2 on 2025-04-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_restaurant_picutreurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurantName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='picutreUrl',
            new_name='picutre',
        ),
    ]
