# Generated by Django 5.2 on 2025-04-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_rename_restaurantname_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picutre',
            field=models.URLField(default='https://i.pinimg.com/736x/19/b1/48/19b148ef0b3b6af0592f6bbb9a2fee68.jpg'),
        ),
    ]
