# Generated by Django 5.2 on 2025-04-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_restaurant_picutre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='picutre',
            new_name='picture',
        ),
    ]
