# Generated by Django 5.2 on 2025-05-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_rename_picutre_restaurant_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('vegetarian', models.BooleanField(default=True)),
                ('picture', models.URLField(default='https://i.pinimg.com/736x/8b/f0/4f/8bf04f38445553c66196f423b74eab1d.jpg')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.restaurant')),
            ],
        ),
    ]
