# Generated by Django 5.2 on 2025-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vegetarian',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
