# Generated by Django 5.2 on 2025-05-19 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_cart_item_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='delivery.cart'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='menu_item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='delivery.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
